# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/realme/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter RMX1931 RMX2081 RMX2086,$(TARGET_DEVICE)),)

endif
